<a href="https://colab.research.google.com/github/AndyJVM/AI2023_AndyVera/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a= np.random.randint(1, 11, (3, 4))
b= np.random.randint(1, 11, (3, 4))
print(a)
print(a.shape)
print(b)
print(b.shape)
print('adding numbers')
print(a+b)
print('subtracting numbers')
print(a-b)
print('multiplier numbers')
print(a*b)


print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[8 7 4 4]
 [6 6 9 6]
 [4 2 7 6]]
(3, 4)
[[ 4  5 10  9]
 [ 2  4  4  3]
 [ 3  2  9  2]]
(3, 4)
adding numbers
[[12 12 14 13]
 [ 8 10 13  9]
 [ 7  4 16  8]]
subtracting numbers
[[ 4  2 -6 -5]
 [ 4  2  5  3]
 [ 1  0 -2  4]]
multiplier numbers
[[32 35 40 36]
 [12 24 36 18]
 [12  4 63 12]]
[[12 12 14 13]
 [ 8 10 13  9]
 [ 7  4 16  8]]
[[32 35 40 36]
 [12 24 36 18]
 [12  4 63 12]]
[[2.         1.4        0.4        0.44444444]
 [3.         1.5        2.25       2.        ]
 [1.33333333 1.         0.77777778 3.        ]]


In [ ]:
a = np.random.randint(1, 11, size=(2, 3))
b = np.random.randint(1, 11, size=(3, 4 ))

print(a)
print(a.shape)
print(b)
print(b.shape)
print(np.dot(a,b))



[[1 9 2]
 [9 8 5]]
(2, 3)
[[5 4 9 3]
 [5 9 9 3]
 [7 1 1 6]]
(3, 4)
[[ 64  87  92  42]
 [120 113 158  81]]


In [ ]:
a= np.random.randint(1, 11, (2, 2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[1 3]
 [1 2]]
[[1 1]
 [3 2]]


In [ ]:
a= np.random.randint(1, 11, (4, 3))
b= np.array((1,0,2))
print(a)
print(a.shape)
print(b)
print(b.shape)

c=np.empty_like(a)

print(c.shape)
print('----------------')
print(c)

[[ 7  1  6]
 [10  7  3]
 [ 3  5  3]
 [ 8  3  3]]
(4, 3)
[1 0 2]
(3,)
(4, 3)
----------------
[[ 9  5  8]
 [10 10  8]
 [10  8  9]
 [ 3  7  9]]


In [ ]:
for i in range(4):
  c[i,:]=a[i,:]+b

print(a)
print(b)
print(c)

c=a+b
print(c)


[[ 7  1  6]
 [10  7  3]
 [ 3  5  3]
 [ 8  3  3]]
[1 0 2]
[[ 8  1  8]
 [11  7  5]
 [ 4  5  5]
 [ 9  3  5]]
[[ 8  1  8]
 [11  7  5]
 [ 4  5  5]
 [ 9  3  5]]


In [ ]:
a=np.array((1,2,3))

print(a)
tmp=np.tile(a,(6,1))
print(tmp)


[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a= np.random.randint(0,10 , (6, 6))
print(a)
aux=np.mean(a)
print(aux)

print(a.mean(axis=1))
print(a.mean(axis=0))


[[7 8 8 2 3 3]
 [5 8 9 9 4 8]
 [9 6 0 1 8 1]
 [6 1 0 4 4 6]
 [2 3 8 3 5 7]
 [2 2 4 4 5 5]]
4.722222222222222
[5.16666667 7.16666667 4.16666667 3.5        4.66666667 3.66666667]
[5.16666667 4.66666667 4.83333333 3.83333333 4.83333333 5.        ]
